import React from 'react';
import { ShieldCheck, AlertCircle } from 'lucide-react';

export const DisclaimerFooter: React.FC = () => {
  return (
    <footer className="bg-slate-900 text-slate-400 text-xs py-10 border-t border-slate-800 pb-20 md:pb-10">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-6">
        
        {/* Safety Box */}
        <div className="bg-slate-800/80 rounded-xl p-4 border border-slate-700/60 flex flex-col md:flex-row items-start gap-3.5">
          <AlertCircle className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
          <div className="space-y-1 text-slate-300 text-[13px] leading-relaxed">
            <p className="font-semibold text-white">
              Medical Information & Non-Diagnostic Disclaimer:
            </p>
            <p>
              MedScan AI is an <strong>educational health information and assistance platform</strong>. It is <strong>NOT a diagnostic medical device</strong> and does not provide medical diagnoses, clinical determinations, or prescription medication advice. Information generated by this system is intended solely for personal understanding and preparatory discussions with licensed healthcare professionals.
            </p>
            <p className="text-amber-300 font-medium">
              If you or someone around you is experiencing severe, sudden, or worsening symptoms—such as chest pain, breathing difficulty, or signs of stroke—immediately call 911 in the United States or your local emergency number elsewhere, or proceed to the nearest emergency department.
            </p>
          </div>
        </div>

        {/* Footer Bottom Links */}
        <div className="flex flex-col sm:flex-row items-center justify-between gap-4 pt-4 border-t border-slate-800">
          <div className="flex items-center gap-2 text-slate-300 font-semibold text-sm">
            <ShieldCheck className="w-4 h-4 text-emerald-400" />
            <span>MedScan AI Health Platform</span>
          </div>
          <div className="flex items-center gap-6 text-[12px] text-slate-400">
            <span>Privacy & HIPAA-Aware Design</span>
            <span>Security Architecture</span>
            <span>Educational Terms</span>
          </div>
          <p className="text-[11px] text-slate-500">
            © {new Date().getFullYear()} MedScan AI. Fictional demo dataset for presentation.
          </p>
        </div>

      </div>
    </footer>
  );
};
